trigger:none

variables:
  imageName: 'amazon-image'
  dockerRegistryServiceConnection: 'B11vish'
  containerRegistry: 'vishvendra89.azurecr.io'
  dockerfilePath: 'Dockerfile'

stages:
- stage: Build
  displayName: Build WAR and Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    - task: Docker@2
      displayName: Build and Push Docker image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          latest
          $(Build.BuildId)
